# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

organization_name: null  # has to be set by user


################################################
#     Networking AWS configuration defaults    #
################################################

# Required by gather networking resources
aws_region: null
aws_vpc_name: "{{ aws_resources_prefix }}-vpc"
aws_security_group_name: "{{ aws_resources_prefix }}-sg"
aws_tag_creator: "{{ organization_name }}"


aws_resources_prefix: "{{ organization_name }}"


##########################################
#     SD-WAN Instances configuration     #
##########################################

# Cloud-init general configurations
admin_username: admin
admin_password: null  # pragma: allowlist secret
vbond_port: 12346
default_vbond_ip: 192.168.1.199  # default ips from official Cisco guides
# vpn0_interface_color: default


###############################
#          Controllers        #
###############################

# vManage
aws_vmanage_ami_id: null
aws_vmanage_instance_type: "c5.9xlarge"

vmanage_default_persona: "COMPUTE_AND_DATA"
site_id_vmanage: 100

vmanage_instances: []

# vBond
aws_vbond_ami_id: null
aws_vbond_instance_type: "c5.large"

site_id_vbond: 200

vbond_instances: []


# vSmart
aws_vsmart_ami_id: null
aws_vsmart_instance_type: "c5.large"

site_id_vsmart: 300

vsmart_instances: []
